[package]
name = "zbl_py"
version.workspace = true
edition = "2021"

[lib]
name = "zbl"
crate-type = ["cdylib"]

[dependencies]
zbl = { path = "../zbl", default-features = false }
thiserror = "2"

[dependencies.pyo3]
version = "0.23"
features = ["extension-module"]
